name: moco_v2_tile_with_overlap
name_in_table_linear: MoCo v2 (${AGGREGATION})
name_in_table_knn: MoCo v2 (${AGGREGATION}) with k=${KNN_N_NEIGHBORS}
model: moco_v2
weights_path: /mnt/nas7/data/Personal/Darya/Checkpoints/superpixel_cluster_clean/no_cluster_bs256_lr0.003_step50_warmup100_epochs100_clusters50_moco_v2/best_model.pth
aggregation:
  - tile_with_overlap
  - whole_roi
tile_size: 224
knn_n_neighbors:
  - 5
  - 20
n_splits: 5
